export const ACTIONS = {
  // Hydration
  HYDRATE: "HYDRATE",

  // Timer
  TIMER_START: "TIMER_START",
  TIMER_PAUSE: "TIMER_PAUSE",
  TIMER_RESET: "TIMER_RESET",
  TIMER_TICK: "TIMER_TICK",
  TIMER_COMPLETE: "TIMER_COMPLETE",
  TIMER_SET_DURATION: "TIMER_SET_DURATION",
  TIMER_SET_TASK: "TIMER_SET_TASK",

  // Tasks
  TASK_ADD: "TASK_ADD",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
  TASK_REORDER: "TASK_REORDER",
  TASK_COMPLETE: "TASK_COMPLETE",

  // Settings
  SETTINGS_UPDATE: "SETTINGS_UPDATE",

  // Onboarding
  ONBOARDING_COMPLETE: "ONBOARDING_COMPLETE",

  // Data
  RESET_ALL_DATA: "RESET_ALL_DATA",
} as const;

export type ActionType = (typeof ACTIONS)[keyof typeof ACTIONS];
